1.	Write a Python Program to Add Two Matrices?
2.	Write a Python Program to Multiply Two Matrices?
3.	Write a Python Program to Transpose a Matrix?
4.	Write a Python Program to Sort Words in Alphabetic Order?
5.	Write a Python Program to Remove Punctuation From a String?


In [14]:
import numpy as np
a=np.random.randint(10,size=(3,3))
b=np.random.randint(10,size=(3,3))    
print(a+b)

[[ 8 13 12]
 [12 14  7]
 [13 13 11]]


In [16]:
#Ans 1
print(a+b)

[[ 8 13 12]
 [12 14  7]
 [13 13 11]]


In [17]:
#Ans 2
a*b

array([[ 7, 40, 35],
       [32, 49, 12],
       [40, 40, 24]])

In [25]:
#Ans 3
a.T

array([[7, 4, 8],
       [5, 7, 5],
       [7, 3, 8]])

In [26]:
#Ans 3
b.T

array([[1, 8, 5],
       [8, 7, 8],
       [5, 4, 3]])

In [28]:
#Ans 4.	Write a Python Program to Sort Words in Alphabetic Order?
l=['google','amazon','oracle','boxing']
sorted(l)

['amazon', 'boxing', 'google', 'oracle']

In [33]:
#Ans 5.	Write a Python Program to Remove Punctuation From a String?
str='priyam..'
a='.'
str.replace(a,'')

'priyam'

In [40]:
a=input('please enter a string')
import re
re.sub(r'[^\w\s]','',a)


please enter a stringfsra./


'fsra'